export const authConstants = {
  SET_IS_AUTHENTICATED: 'SET_IS_AUTHENTICATED',
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  GET_USERINFO_START: 'GET_USERINFO_START',
  GET_USERINFO_SUCCESS: 'GET_USERINFO_SUCCESS',
  GET_USERINFO_FAILURE: 'GET_USERINFO_FAILURE',
};

export const globalAlertConstants = {
  SHOW_ALERT: 'SHOW_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
  CLEAR_ALL: 'CLEAR_ALL',
};

export const appConstants = {
  START_BOOTSTRAP: 'START_BOOTSTRAP',
  SET_IS_LOADED: 'SET_IS_LOADED',
};

export const profileConstants = {
  GET_PROFILE_START: 'GET_PROFILE_START',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
  DELETE_PROFILE_EXPERIENCE_START: 'DELETE_PROFILE_EXPERIENCE_START',
  DELETE_PROFILE_EXPERIENCE_SUCCESS: 'DELETE_PROFILE_EXPERIENCE_SUCCESS',
  DELETE_PROFILE_EXPERIENCE_FAILURE: 'DELETE_PROFILE_EXPERIENCE_FAILURE',
};
