export const authConstants = {
  SET_IS_AUTHENTICATED: 'SET_IS_AUTHENTICATED',
  FETCH_USERINFO_START: 'FETCH_USERINFO_START',
  FETCH_USERINFO_SUCCESS: 'FETCH_USERINFO_SUCCESS',
  FETCH_USERINFO_FAILURE: 'FETCH_USERINFO_FAILURE',
};

export const globalAlertConstants = {
  SHOW_ALERT: 'SHOW_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
  CLEAR_ALL: 'CLEAR_ALL',
};
