export const authConstants = {
  SET_IS_AUTHENTICATED: 'SET_IS_AUTHENTICATED',
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  GET_USERINFO_START: 'GET_USERINFO_START',
  GET_USERINFO_SUCCESS: 'GET_USERINFO_SUCCESS',
  GET_USERINFO_FAILURE: 'GET_USERINFO_FAILURE',
};

export const globalAlertConstants = {
  SHOW_ALERT: 'SHOW_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
  CLEAR_ALL: 'CLEAR_ALL',
};

export const appConstants = {
  START_BOOTSTRAP: 'START_BOOTSTRAP',
  SET_IS_LOADED: 'SET_IS_LOADED',
};
